name: Build on Windows
on: push
jobs:
  Setup:
    runs-on: windows-latest
    steps:
      - name: chocoperl
      - run: choco install gh
      - run: gh version
      - run: cmd.exe /c perl -v
      - run: choco uninstall strawberryperl
      - run: choco install strawberryperl
      - run: C:\Strawberry\perl\bin\perl -v

  Checkout:
      - name: Checkout
        uses: actions/checkout@v4
