name: Build on Windows
on: push
jobs:
  perl-compile:
    runs-on: windows-latest
    steps:
      - name: chocoperl
        run: |
              choco install gh
              gh version
              cmd.exe /c perl -v
              choco uninstall strawberryperl
              choco install strawberryperl
              C:\Strawberry\perl\bin\perl -v

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: perl

      - name: compile
        run: |
              cd D:\a\ReplayConfig\ReplayConfig\perl\
              C:\Strawberry\perl\bin\pp.bat D:\a\ReplayConfig\ReplayConfig\perl\replay-config.pl -o D:\a\ReplayConfig\ReplayConfig\perl\replay-config.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: replayconfig-win64.exe
          path: |
                perl\replayconfig_win64.exe
