name: Build on Windows
on: 
  push:
    tags:
      - '*'

jobs:
  perl-compile:
    runs-on: windows-latest
    steps:
      - name: chocoperl
        run: |
              choco install gh
              gh version
              cmd.exe /c perl -v
              choco uninstall strawberryperl
              choco install strawberryperl
              C:\Strawberry\perl\bin\perl -v

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: perl

      - name: compile
        run: |
              cd D:\a\ReplayConfig\ReplayConfig\perl\
              C:\Strawberry\perl\bin\pp.bat D:\a\ReplayConfig\ReplayConfig\perl\replay-config.pl -o D:\a\ReplayConfig\ReplayConfig\perl\replay-config.exe

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: ${{ github.ref }}
        env:
            GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: replay-config_win64.exe
          path: |
                perl\replay-config.exe

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: perl\replay-config.exe
            asset_name: replay-config_win64.exe
            asset_content_type: application/exe
