name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: choco install gh strawberryperl
      - run: gh version
      - run: cmd.exe /c perl -v
      - run: C:\Strawberry\perl\bin\perl -v
