name: CI

on: [push, pull_request]

job:
  build-windows-64:
    runs-on: windows-latest
    steps:
    - uses: shogo82148/actions-setup-perl@v1
    with:
      perl-version: "5.32"
      distribution: strawberry
  - run: cpanm --installdeps .
  - run: prove -lv t

    - name: Checkout script
      uses: actions/checkout@v4
      with:
        repository: Pokefinder-org/ReplayConfig
        path: perl

    - name: Build
      run: cmd.exe /c perl -v

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: replayconfig-win64
        path: |
           replayconfig_win64.exe
