name: Build on Windows
on: push
jobs:
  perl-compile:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: perl

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: ${{ github.ref }}
        env:
            GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: replay-config_winxx.exe
          path: |
                perl\replay-config.pl

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: perl\replay-config.pl
            asset_name: replay-config_winxx.exe
            asset_content_type: application/exe
