name: Build on Windows
on: push
jobs:
  Setup:
    runs-on: windows-latest
    steps:
      - run: choco install gh
      - run: gh version
      - run: cmd.exe /c perl -v
      - run: choco uninstall strawberryperl
      - run: choco install strawberryperl
      - run: C:\Strawberry\perl\bin\perl -v

  Checkout:
      uses: actions/checkout@v4
      with:
        repository: Pokefinder-org/ReplayConfig
        path: perl

  Build:
      steps:
      - run: cmd.exe /c perl -v
      - run: cmd.exe /c C:\Strawberry\perl\bin\pp -o C:\perl\replayconfig_win64.exe C:\perl\replayconfig.pl

  Upload:
      uses: actions/upload-artifact@v3
      with:
        name: replayconfig-win64
        path: perl
           replayconfig_win64.exe
